apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prytaneum-ingress
  namespace: development
  annotations:
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/v1beta1.FrontendConfig: "prytaneum-frontend-config"
    kubernetes.io/ingress.allow-http: "true"
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: prytaneum-client-service
            port: 
              number: 80
        path: /*
        pathType: ImplementationSpecific
      - backend:
          service:
            name: prytaneum-server-service
            port:
              number: 80
        path: /graphql
        pathType: ImplementationSpecific
